ыаваы

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -63,9 +63,18 @@ jobs:
       with:
         submodules: true
     - run: brew install sfml
-    - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_INSTALL_PREFIX=`pwd`/install
-    - run: cmake --build . --target install # Install first
-    - run: cpack -G ZIP # Explicitly specify ZIP generator
+    - name: Configure CMake
+      run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_INSTALL_PREFIX=./install
+    - name: Build and Install
+      run: cmake --build . --target install
+    - name: Package with CPack
+      run: |
+        mkdir -p dist # create a distribution directory
+        cpack -G ZIP -C dist # specify the output path explicitly
+          if [ ! -f "dist/physics-0.0.${{ github.run_number }}-Darwin.zip" ]; then
+          echo "Error: CPack failed to create the package."
+          exit 1
+        fi
     - name: Run Tests
       run: |
         ctest --output-on-failure || exit 1
@@ -73,7 +82,7 @@ jobs:
       id: create_release_macos
       uses: actions/create-release@v1
       env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: ${{ github.run_number }}
         release_name: Release ${{ github.run_number }} (MacOS)
@@ -83,10 +92,10 @@ jobs:
       id: upload-release-asset-macos
       uses: actions/upload-release-asset@v1
       env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
-        asset_path: ./install/physics-0.0.${{ github.run_number }}-Darwin.zip #Path changed
+        asset_path: ./dist/physics-0.0.${{ github.run_number }}-Darwin.zip
         asset_name: physics-0.0.${{ github.run_number }}-Darwin.zip
         asset_content_type: application/zip
 
